apiVersion: v2
name: redis
description: Redis wrapper chart (usa Bitnami come dipendenza)
type: application
version: 0.1.0
appVersion: "7"

dependencies:
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis
